<?php
/**
 * Change: default layout
 * Themes: JustBlack theme
 *
 */
?>
<?php use Fisharebest\Webtrees\Auth; ?>
<?php use Fisharebest\Webtrees\DebugBar; ?>
<?php use Fisharebest\Webtrees\FlashMessages; ?>
<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\Theme; ?>
<?php use Fisharebest\Webtrees\View; ?>
<?php use Fisharebest\Webtrees\Webtrees; ?>

<!DOCTYPE html>
<html <?=I18N::htmlAttributes() ?>>

<head>
    <meta charset="UTF-8">
    <meta name="csrf" content="<?= e(csrf_token()) ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="<?= e($meta_robots ?? 'noindex,nofollow') ?>">
    <meta name="generator" content="<?= e(Webtrees::NAME) ?>">
    <?php if ($tree !== null): ?>
    <meta name="description" content="<?= e($tree->getPreference('META_DESCRIPTION')) ?>">
    <?php endif ?>

    <title>
        <?= strip_tags($title) ?>
        <?php if ($tree !== null && $tree->getPreference('META_TITLE') !== ''): ?>
        –
        <?= e($tree->getPreference('META_TITLE')) ?>
        <?php endif ?>
    </title>

    <link rel="icon" href="<?= Theme::theme()::ASSET_DIR ?>favicon.png" type="image/png">
    <link rel="icon" type="image/png" href="<?= Theme::theme()::ASSET_DIR ?>favicon192.png" sizes="192x192">
    <link rel="apple-touch-icon" sizes="180x180" href="<?= Theme::theme()::ASSET_DIR ?>favicon180.png">

    <?php /* Load the theme stylesheets */ ?>
    <link rel="stylesheet" type="text/css" href="<?= e(Theme::theme()::STYLESHEET) ?>">

    <?= View::stack('styles') ?>

    <?= Theme::theme()->analytics() ?>

    <?= DebugBar::renderHead() ?>
</head>

<body class="wt-global<?= Theme::theme()->getThemeGlobalClass() ?>">
    <header class="wt-header-wrapper">
        <div class="container-fluid wt-header-container">
            <div class="d-flex flex-wrap wt-header-content m-0">
                <div class="wt-accessibility-links">
                    <a class="sr-only sr-only-focusable btn btn-info btn-sm" href="#content">
                        <?= /* I18N: Skip over the headers and menus, to the main content of the page */ I18N::translate('Skip to content') ?>
                    </a>
                </div>

                <div class="d-flex col order-2">
                    <div class="col wt-site-logo"></div>
                    <?php if ($tree !== null): ?>
                    <h1 class="col jc-site-title align-self-end text-right px-5 pb-3">
                        <a href="index.php?route=tree-page&ged=<?= e($tree->name()) ?>">
                            <?= e($tree->title()) ?></a>
                    </h1>
                    <?php endif ?>
                </div>

                <div class="d-flex flex-column flex-nowrap col-12 order-1">
                    <div class="col wt-secondary-navigation">
                        <ul class="nav wt-secondary-menu">
                            <?php foreach (Theme::theme()   ->secondaryMenu() as $menu) : ?>
                            <?= $menu->bootstrap4() ?>
                            <?php endforeach ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="jc-favsearch-bar d-flex flex-nowrap justify-content-between align-items-center">
            <?php if ($tree !== null): ?>
            <div class="col-3 jc-header-favorites">
                <ul class="jc-favorites-dropdown" role="menubar"><?= Theme::theme()->menuFavorites() ?></ul>
            </div>
            <div class="col-3 jc-header-search">
                <form class="wt-header-search-form" role="search">
                    <input type="hidden" name="route" value="search-quick">
                    <input type="hidden" name="ged" value="<?= e($tree->name()) ?>">
                    <div class="input-group">
                        <label class="sr-only" for="quick-search">
                            <?= I18N::translate('Search') ?></label>
                        <input type="search" class="form-control wt-header-search-field" id="quick-search" name="query"
                            size="15" placeholder="<?= I18N::translate('Search') ?>">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn-primary wt-header-search-button">
                                <?= view('icons/search') ?>
                            </button>
                        </span>
                    </div>
                </form>
            </div>
            <?php endif ?>
        </div>

        <?php if ($tree !== null): ?>
        <nav class="col wt-primary-navigation">
            <ul class="nav wt-primary-menu">
                <?php foreach (Theme::theme()->primaryMenu($individual ?? $tree->significantIndividual(Auth::user())) as $menu): ?>
                <?= $menu->bootstrap4() ?>
                <?php endforeach ?>
            </ul>
        </nav>
        <?php endif ?>
    </header>

    <div class="jc-divider"></div>
    <?= Theme::theme()->fancyImagebar(); ?>

    <main id="content" class="container<?= Theme::theme()->setFluidClass() ?> wt-main-wrapper mt-3">
        <div class="wt-main-container">
            <div class="flash-messages">
                <?php foreach (FlashMessages::getMessages() as $message): ?>
                <div class="alert alert-<?= e($message->status) ?> alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="<?= I18N::translate('close') ?>">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <?= $message->text ?>
                </div>
                <?php endforeach ?>
            </div>

            <?= $content ?>
        </div>
    </main>

    <div class="jc-divider"></div>

    <footer class="wt-footer-container bg-faded py-3">
        <div class="jc-footer-content d-flex align-items-end d-print-none">
            <div class="jc-footer-item col-md-4 text-left">
                <?= Theme::theme()->formatContactLinks() ?>
            </div>

            <div class="jc-footer-item col-md-4 text-center">
                <?php if ($page_hits ?? 0 > 0): ?>
                <div class="wt-page-views">
                    <?= I18N::plural(
	'This page has been viewed %s time.',
	'This page has been viewed %s times.',
	$page_hits,
						'<span class="odometer">' . I18N::digits($page_hits) . '</span>'
) ?>
                </div>
                <?php endif ?>
            </div>

            <div class="jc-footer-item col-md-4 text-right">
                <div class="credits d-flex flex-column">
                    <?= Theme::theme()->logoPoweredBy() . Theme::theme()->designerUrl() ?>
                </div>
            </div>
        </div>
    </footer>
    <div class="flash-messages">
        <?php if (Theme::theme()->cookieWarning()): ?>
        <?= Theme::theme()->htmlAlert(Theme::theme()->cookieWarning(), 'info', true) ?>
        <?php endif ?>
    </div>

    <script src="<?= e(Webtrees::ASSETS_PATH . 'js/vendor.js') ?>?<?= filemtime(WT_ROOT . Webtrees::ASSETS_PATH . 'js/vendor.js') ?>"></script>
    <script src="<?= e(Webtrees::ASSETS_PATH . 'js/webtrees.js') ?>?<?= filemtime(WT_ROOT . Webtrees::ASSETS_PATH . 'js/webtrees.js') ?>"></script>

    <script>
    var AUTH_ID = "<?= Auth::id() ?>";
    var COLORBOX_ACTION_FILE = "themes/<?= Theme::theme()::THEME_DIR ?>/resources/colorbox.php";
    var WT_BASE_URL = "<?= WT_BASE_URL ?>";
    </script>

    <script src="<?= e(Theme::theme()::JAVASCRIPT) ?>"></script>

    <?= View::stack('javascript') ?>

    <?= DebugBar::render() ?>
</body>

</html>
